In [194]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as st
import statsmodels.api as sm
import statsmodels.formula.api as smf
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
import altair as alt

In [2]:
o = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='GeneralSbs')
ost = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='GeneralSt')
tf = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='TFlight')
tc = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='TContact')
e = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='Elevation')
pw = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='Power')
pc = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='Pace')
rsi = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='RSI')
wpx = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='WPX')
wpy = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='WPY')
sw = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='StepWidth')
nj = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='NJ')
d = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='Distance')
tt = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='TTotal')
tp = pd.read_excel('OptoJumpSorted.xlsx', sheet_name='TPoints')

In [3]:
#swap
tt.loc[:40, 'Test'] = 'final'
tt.loc[40:, 'Test'] = 'initial'

In [4]:
df_list = [tf, tc, e, pw, pc, rsi, wpx, wpy, sw, nj, d, tp]
melt_df_list = []
for df in df_list:
    df.loc[:,'Test'] = tt.loc[:,'Test']    #swap
    melt_df_list = melt_df_list + [pd.melt(df, id_vars=['Name','Test','Group','Sex','NJumps', 'Mean'], 
                                   value_vars=range(1,170), var_name='Jump', value_name='val')]

In [5]:
melt_df_list_timed = []
for df in melt_df_list:
    melt_df_timed = df.copy()
    melt_df_timed['time'] = melt_df_list[11].val
    melt_df_list_timed = melt_df_list_timed + [melt_df_timed]

In [6]:
values = ['Flight Time (s)', 'Contact Time (s)', 'Elevation (cm)', 'Propulsive Power (W/Kg)', 'Pace (jumps/s)', 'RSI (m/s)', 'StepWidth (mm)',
'Distance (cm)']
keys = [0, 1, 2, 3, 4, 5, 8, 10]
dict = {k: v for k, v in zip(keys, values)}
dict

{0: 'Flight Time (s)',
 1: 'Contact Time (s)',
 2: 'Elevation (cm)',
 3: 'Propulsive Power (W/Kg)',
 4: 'Pace (jumps/s)',
 5: 'RSI (m/s)',
 8: 'StepWidth (mm)',
 10: 'Distance (cm)'}

In [8]:
melt_df_list[2]

      Name     Test Group Sex  NJumps       Mean Jump   val
0       o1    final     J   F     122   4.324590    1   8.4
1       o2    final     B   M     135   4.351111    1   6.3
2       o3    final     J   F     105   9.558095    1  10.6
3       o4    final     B   F     122   6.707377    1  11.3
4       o5    final     J   M     104  10.629808    1  11.3
...    ...      ...   ...  ..     ...        ...  ...   ...
13515  o36  initial     B   M     135   2.478519  169   NaN
13516  o37  initial     J   M     149   3.192617  169   NaN
13517  o38  initial     J   M     133   2.611278  169   NaN
13518  o39  initial     B   M     161   3.662112  169   NaN
13519  o40  initial     J   F     147   2.782313  169   NaN

[13520 rows x 8 columns]

In [ ]:
px.violin(melt_df_list[2], x='Test', y='val', facet_row='Group', color='Sex',
          color_discrete_sequence=['darkorange', 'darkseagreen'],
          violinmode='group', template='simple_white',
          width=1000, height=700,box=True
          ).update_traces(marker_line_color='black',
                          box_fillcolor='rgba(0,0,0,0.4)',
                          marker_size=1.2, 
                          jitter=0.4,
                          meanline_color='black',
                          points='all')

In [94]:
print(px.violin(melt_df_list[2], x='Test', y='val', facet_row='Group', color='Sex',
          color_discrete_sequence=['darkorange', 'darkseagreen'],
          violinmode='group', template='simple_white',
          width=1000, height=700,box=True
          ).update_traces(marker_line_color='black',
                          box_fillcolor='rgba(0,0,0,0.4)',
                          marker_size=1.2, 
                          jitter=0.4,
                          meanline_color='black',
                          points='all'))

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'fillcolor': 'rgba(0,0,0,0.4)', 'visible': True},
              'hovertemplate': 'Sex=F<br>Group=J<br>Test=%{x}<br>val=%{y}<extra></extra>',
              'jitter': 0.4,
              'legendgroup': 'F',
              'marker': {'color': 'darkorange', 'line': {'color': 'black'}, 'size': 1.2},
              'meanline': {'color': 'black'},
              'name': 'F',
              'offsetgroup': 'F',
              'orientation': 'v',
              'points': 'all',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': array(['final', 'final', 'final', ..., 'initial', 'initial', 'initial'],
                         shape=(2028,), dtype=object),
              'x0': ' ',
              'xaxis': 'x2',
              'y': {'bdata': ('zczMzMzMIEAzMzMzMzMlQGZmZmZmZi' ... 'AAAAAA+H8AAAAAAAD4fwAAAAAAAPh/'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y2'},
             {'alignmentgroup': 'True',
              'box': {'fillcolor': 'rgba(0,0,0,0.4)', 'visible': True},
              'hovertemplate': 'Sex=F<br>Group=B<br>Test=%{x}<br>val=%{y}<extra></extra>',
              'jitter': 0.4,
              'legendgroup': 'F',
              'marker': {'color': 'darkorange', 'line': {'color': 'black'}, 'size': 1.2},
              'meanline': {'color': 'black'},
              'name': 'F',
              'offsetgroup': 'F',
              'orientation': 'v',
              'points': 'all',
              'scalegroup': 'True',
              'showlegend': False,
              'type': 'violin',
              'x': array(['final', 'final', 'final', ..., 'initial', 'initial', 'initial'],
                         shape=(3042,), dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('mpmZmZmZJkAAAAAAAADwPwAAAAAAAB' ... 'AAAAAA+H8AAAAAAAD4fwAAAAAAAPh/'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'fillcolor': 'rgba(0,0,0,0.4)', 'visible': True},
              'hovertemplate': 'Sex=M<br>Group=J<br>Test=%{x}<br>val=%{y}<extra></extra>',
              'jitter': 0.4,
              'legendgroup': 'M',
              'marker': {'color': 'darkseagreen', 'line': {'color': 'black'}, 'size': 1.2},
              'meanline': {'color': 'black'},
              'name': 'M',
              'offsetgroup': 'M',
              'orientation': 'v',
              'points': 'all',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': array(['final', 'final', 'final', ..., 'initial', 'initial', 'initial'],
                         shape=(3380,), dtype=object),
              'x0': ' ',
              'xaxis': 'x2',
              'y': {'bdata': ('mpmZmZmZJkAAAAAAAAAMQJqZmZmZmR' ... 'AAAPh/AAAAAAAA+H8AAAAAAAD4fw=='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y2'},
             {'alignmentgroup': 'True',
              'box': {'fillcolor': 'rgba(0,0,0,0.4)', 'visible': True},
              'hovertemplate': 'Sex=M<br>Group=B<br>Test=%{x}<br>val=%{y}<extra></extra>',
              'jitter': 0.4,
              'legendgroup': 'M',
              'marker': {'color': 'darkseagreen', 'line': {'color': 'black'}, 'size': 1.2},
              'meanline': {'color': 'black'},
              'name': 'M',
              'offsetgroup': 'M',
              'orientation': 'v',
              'points': 'all',
              'scalegroup': 'True',
              'showlegend': False,
              'type': 'violin',
              'x': array(['final', 'final', 'final', ..., 'initial', 'initial', 'initial'],
                         shape=(5070,), dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('MzMzMzMzGUDNzMzMzMwIQAAAAAAAAA' ... 'AAAAAA+H8AAAAAAAD4fwAAAAAAAPh/'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'annotations': [{'font': {},
                                'showarrow': False,
                                'text': 'Group=B',
                                'textangle': 90,
                                'x': 0.98,
                                'xanchor': 'left',
                                'xref': 'paper',
                                'y': 0.2425,
                                'yanchor': 'middle',
                                'yref': 'paper'},
                               {'font': {},
                                'showarrow': False,
                                'text': 'Group=J',
                                'textangle': 90,
                                'x': 0.98,
                                'xanchor': 'left',
                                'xref': 'paper',
                                'y': 0.7575000000000001,
                                'yanchor': 'middle',
                                'yref': 'paper'}],
               'height': 700,
               'legend': {'title': {'text': 'Sex'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'violinmode': 'group',
               'width': 1000,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 0.98], 'title': {'text': 'Test'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 0.98], 'matches': 'x', 'showticklabels': False},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 0.485], 'title': {'text': 'val'}},
               'yaxis2': {'anchor': 'x2', 'domain': [0.515, 1.0], 'matches': 'y', 'title': {'text': 'val'}}}
})

In [124]:
px.line(melt_df_list[2], x='Jump', y='val', color='Test', line_dash='Name', template='ggplot2', 
        color_discrete_sequence=['tomato','darkseagreen'], line_shape='spline').update_traces(line_width=1)
# stackgroup='Jump'

In [160]:
px.scatter(a, x='time', y='val', color='Test').update_traces(marker_size=2.5)

In [195]:
a = melt_df_list_timed[2].copy()

In [184]:
px.imshow(e.loc[:,1:169])

In [185]:
w = pd.read_csv('ws.csv')

In [186]:
w

,Index,id,group,time,rank,total,1,2,3,4,...,10,11,12,13,14,15,16,17,18,19
0,1,w1,J,initial,6,12.73,0.57,0.67,0.79,0.62,...,0.52,0.60,0.74,0.51,0.67,0.56,1.22,0.70,0.00,0.96
1,2,w2,B,initial,17,11.74,0.32,0.48,1.46,0.53,...,0.61,0.20,0.60,0.69,0.52,0.68,0.56,0.64,0.41,0.49
2,3,w3,J,initial,5,12.42,0.56,0.68,0.53,0.59,...,0.88,0.68,0.62,0.69,0.69,0.63,0.64,0.67,0.73,0.59
3,4,w4,B,initial,18,11.80,0.60,0.51,0.80,0.69,...,0.45,0.53,0.68,0.59,0.79,0.58,0.70,1.06,0.60,0.22
4,5,w5,J,initial,16,20.62,1.23,0.90,1.11,0.78,...,1.30,0.76,0.94,0.77,0.68,1.68,3.47,0.85,0.93,0.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,76,w36,B,final,1,9.63,0.55,0.50,0.49,0.55,...,0.49,0.54,0.50,0.45,0.38,0.32,0.81,0.45,0.47,0.56
76,77,w37,J,final,16,15.88,0.14,0.67,0.81,0.59,...,0.74,0.65,0.60,0.64,0.62,0.79,0.67,0.64,4.18,0.80
77,78,w38,J,final,5,10.65,0.55,0.55,0.59,0.54,...,0.64,0.53,0.43,0.62,0.56,0.55,0.64,0.67,0.59,0.56
78,79,w39,B,final,6,10.68,0.52,0.45,0.40,0.61,...,0.66,0.57,0.57,0.68,0.58,0.43,0.66,0.75,0.58,0.43
79,80,w40,J,final,2,10.09,0.54,0.37,0.35,0.54,...,0.38,0.44,0.58,0.64,0.55,0.49,0.61,0.37,0.71,0.54

In [193]:
px.imshow(w.loc[:,'1':].T)

In [209]:
alt.data_transformers.disable_max_rows()
base = alt.Chart(a).mark_circle(opacity=0.5, size=10).encode(
    alt.X('time:Q'),
    alt.Y('val:Q'),
    alt.Color('Test:N')
).properties(
    width=1100,
    height=300
)

base + base.transform_loess('time', 'val', groupby=['Test']).mark_line(size=2)

alt.LayerChart(...)